{
 "title": "factor dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "moisture factor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "moisture_factor" }
   ]
  },
  {
   "title": "thickness factor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "thickness_factor" }
   ]
  },
  {
   "title": "moisture",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "moisture" }
   ]
  },
  {
   "title": "thickness",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "thickness" }
   ]
  }
 ]
}