name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # check-ot our repository
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      # install app dependencies
      - name: Install dependencies
        run: |
          npm install
          npm ci

      # Testing our apps
      - name: Testing
        run: npm test

  BuildDockerImage:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      # Install doctl
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Build container image
      - name: Build container image
        run: docker build -t registry.digitalocean.com/nycu-cn-team-8/apc-simulator:$(echo $GITHUB_SHA | head -c7) .

  PushdDockerImage:
    needs: BuildDockerImage
    runs-on: ubuntu-latest
    steps:
      # Log in to DigitalOcean
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      # Push image to DigitalOcean Container Registry
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/nycu-cn-team-8/apc-simulator:$(echo $GITHUB_SHA | head -c7)

  DeployAndVerigy:
    needs: PushdDockerImage
    runs-on: ubuntu-latest
    steps:
      # Update deployment file
      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|{{IMAGE}}|${{ secrets.REGISTRY_ENDPOINT }}/apc-simulator:'${TAG}'|' $GITHUB_WORKSPACE/infra/app/deployment.yml

      # Save DigitalOcean kubeconfig with short-lived credentials
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/infra/app/deployment.yml

      - name: Verify deployment
        run: kubectl rollout status deployment/apc-simulator