name: CI/CD
on:
  push:
    branches:
      - testCICD_no_failed
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # check-ot our repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      # install app dependencies
      - name: Install dependencies
        run: |
          npm install
          npm ci
      
      # Testing our apps
      - name: Testing
        run: npm test
      
      # Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ming-ouo/cloud-native-final-project
          tag_with_ref: true
          tag_with_sha: true
        
  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout files    
        uses: actions/checkout@v2
        
      - name: Get tag name
        uses: olegtarasov/get-tag@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
         
      - name: Provision Droplet and deploy container
        run: doctl compute droplet create "$GIT_TAG_NAME" --image docker-18-04 --size s-1vcpu-1gb --region nyc1 --user-data-file deploy.sh --wait

